### ISSUE TITLE
Previously Loggged In Question

### ISSUE THREAD

**Issue by coollbv** [jjjchens235/bing-rewards#116]
Is there a way to turn that feature off? To see if you have logged in previously on the device? I primarily use Firefox for searches (I found it more reliable) and from what it seems although it uses chromium this script doesn't recognize that?
What is the purpose of that feature anyway?

**Comment by jjjchens235** [comment]
fair point, i'll add it as a command line option in the up-coming future.

the intention of this feature is based on the following (issue #78 :

The problem with accepting everytime highlights a bigger problem : Microsoft detect bots by listing accounts that connect multiple time with new browser with the same IP.
Saving cookies instead of connecting everytime would mimic more acurately a browser's behavior

**Comment by coollbv** [comment]
Thank you - I prefer to search in incognito and NOT give MS any additional info then I already need anyways...

**Comment by jjjchens235** [comment]
Makes sense, it should be an easy fix so I'll prioritize it, in the interim, you can use the email and password flags in the command line args, that skips the cookies.

**Comment by coollbv** [comment]
Yes, I've used -e and -p but got the pesky you need to log in on the browser first message lol.

**Comment by jjjchens235** [comment]
I believe you're going to get that message cookie or no cookies.
It indicates that you need to manually log once in your _actual_ chrome browser so that Microsoft recognizes your account.

This feature has been completed, going forward you just need to use the `-nc` option.
