### ISSUE TITLE
[Feature request] Please add # of collected points to the log

### ISSUE THREAD

**Issue by sensboston** [jjjchens235/bing-rewards#136]
Could you please add as a last line in the "error.log" (or any log) number of points collected by specific account? 
Thank you!

**Comment by coollbv** [comment]
It would actually be best if there is a separate points.log with Available and Today points (maybe even points for the month?)

**Comment by sensboston** [comment]
Agree, separate log file will be helpful, but as for me, I'm interested in the actual points only (or message if account blocked).

**Comment by MindScape00** [comment]
I believe this already exists? My error.log outputs a 'Summary' at the end that shows how many points were gathered today, the streak count, and total points available.

**Comment by coollbv** [comment]
There is no separate log and for some reason (I presume permissions) the error.log doesn't always populate for me.

**Comment by MindScape00** [comment]
> There is no separate log and for some reason (I presume permissions) the error.log doesn't always populate for me.

The original ‘issue’ mentioned putting it possibly in error.log, hence the request is technically completed. Your issue with error.log not populating from presumable permission issues wouldn’t be solved by another log file, as they’d likely have the same permissions issues then.  Odd tho, I don’t have permission issues like such and I’m running it usually on a domain managed pc

**Comment by sensboston** [comment]
> My error.log outputs a 'Summary' at the end that shows how many points were gathered today
Not all the time: in case of exception, last lines of the **error.log** file will contain exception details. 
I suggest to @jjjchens235 to make last line of **error.log** (for every run) persistent: output number of point and/or account status (if banned).

**Comment by jjjchens235** [comment]
I'll leave this issue open, but unfortunately, I'm not going to prioritize this issue as I think there are other features that would benefit more people. Of course, a PR is always welcome.

If I were to do this, I would probably create a separate log file storing points per coollbv's suggestion. Each time print_stats() is called, the stats_log file would be written to.

The intention of error.log is to store only errors. The reason why the error.log is showing summary info is because when all searches are NOT completed, everything that was printed to the console is also written to error.log.

And because the program currently always deems 'offers' to have failed, it's always writing to the error.log. I hope to fix the offer status issue in the near future, and as a byproduct, error.log should rarely have summary info written to it.

**Comment by coollbv** [comment]
Bot works wonderfully as is - little tweeks and add ons are just gravy on top... Thank you!!!
