### ISSUE TITLE
Rework remaining mode completion tracking & Log file generation

### ISSUE THREAD

**Issue by JartanFTW** [jjjchens235/bing-rewards#166]
Currently, remaining mode operates based on logs from the last time the program was run. If everything was completed successfully, the program wont do anything unless the time is past 00:00 PST, even if new tasks are available.

I propose that we change remaining to log in and check if anything can be completed, rather than basing off log files.

Along with this, the program launches a different web driver for mobile search, web search, and edge search, even if it doesn't need to complete one of them (it closes the driver after realizing). I suggest that instead of checking the completion after launching the driver, we check using the provided data in https://rewards.microsoft.com/pointsbreakdown which provides all we need I believe. It was also mentioned in #163 that the "new dashboard method" could be used for this, but I haven't looked into this.

Along with this, since this idea will be removing the use of log files for tracking completion, it may also be a good time to acknowledge that if a user uses the same instance of the program with two different accounts (switching out or using parameters, or something), both accounts use the same log files. I suggest each account getting it's own log file named based on the account. This prevents interference between different accounts. This is not adding multi-account support, this is just preventing issues from arising when switching accounts.

Let me know thoughts on these ideas.

**Comment by jjjchens235** [comment]
You brought up 3 issues
1. Determining if any searches can be completed
2. Different web drivers for each search type
3. Log file structure

### Determining if any searches can be completed
**The issue**: the program won't do anything unless the time is past 00:00 PST, even if new tasks are available.
**Proposed Solution**: Log-in and check the dashboard, to determine what still needs to be completed, rather than base this on the log file.
**My POV**: Fine with me. I suppose that the only disadvantage would be the extra 15-30 seconds it takes to log in to determine account status, but if it ends up being more robust then that's worth the sacrifice.

### Different web-driver
**Issue**: Driver is opened even if not necessary.
**My POV**: Assuming you're using --remaining, I don't think this is true. It only completes what is necessary and uses as few driver instances as possible. The only time it uses both driver instances is if both -web and -mobile need to be completed.

Note that this change was introduced in the last few weeks only.

### multiple accounts with log files
I have spent some time thinking about this issue. 
Multiple log files, one for each user would work, but I would prefer keeping one log file, and storing the data as json
```json
{
  "account1": [
    {
      "2022-07-01 19:59:59": "Failed Mobile Search"
    },
    {
      "2022-12-01 19:59:59": "Failed Web Search"
    }
  ],
  "account2": []
}

```

**Comment by JartanFTW** [comment]
You summed this up very well, and what you described for the third issue is a good idea.
For the second, it's ultimately possible that I was misinterpreting what I was seeing and the drivers were closing due to the issue with not enough queries that we're currently working on in #163. Lets disregard the second issue for now, and I'll bring it back up in a different thread if I still notice it after everything else is finished (it's low-priority anyway).

**Comment by JartanFTW** [comment]
One more issue:

Issue: Between each search, the program goes back to the dashboard to check if it's finished.
Reason why this is bad: This consumes quite a lot of bandwidth, slows down progress, and likely contributes to Microsoft's annoyance 
Proposed solution: I suggest we make it estimate how many more searches to do, and check back at the end of the estimate, creating a new estimate if it's not finished.

**Comment by jjjchens235** [comment]
The original reason for checking the progress each time was to make sure that searches weren't stalling. I would still like to keep that functionality to some degree.
As long as the estimated function can maintain some check for this, then I'm all for it- great idea!

**Comment by jjjchens235** [comment]
I think there are 3 (actual) issues /enhancements to be addressed here:

1. Determining if any searches can be completed (pst issue)
2. Log file structure (run.log by account)
3. check progress estimator

Do you mind splitting these into separate issues, and assigning a priority label  (p1-p3) based on which you would like to have completed first?

**Comment by jjjchens235** [comment]
I have created separate issues for each of these:

- Determining if any searches can be completed (pst issue) - `won't do`
- Log file structure (run.log by account) - `completed` 
- search progress estimator - `slated for dev`

Closing this now. I appreciate all of your help and input, you've brought up TONS of insightful points.
