### ISSUE TITLE
Headless and Multiple Accounts

### ISSUE THREAD

**Issue by pearlheartgtr** [jjjchens235/bing-rewards#20]
Thank you for uploading this.

Will there be a headless mode and support multiple accounts?

I had the "other" setup and lost it when my hard drive died right after the old one was taken down.

**Comment by jjjchens235** [comment]
No problem! Are you referring to the old set-up from mid 2018?

Headless mode is still supported. I just tested it and it worked flawlessly for all searches and offers. I originally had changed it to False because there was a time when it wasn't working as consistently as non-headless mode.

You can turn it back on inside the file BingRewards.py, line 18 by making
HEADLESS                   = True

With regards to multiple accounts, I think the original author was asked the same question and he had responded "no" as it wasn't in the spirit of the project. I'm inclined to agree for now.

**Comment by pearlheartgtr** [comment]
Thank you!

I was thinking of the xMNG rewards that was deleted a month or so ago. But this works way faster. I have 3 accounts, each with their own folder, and it's still faster.

Also, does this randomize search times?

**Comment by jjjchens235** [comment]
Oh interesting! 
Did you mean this version works slower than the xMNG one?

Yes search times are randomized.

**Comment by pearlheartgtr** [comment]
No, this version is faster.

**Comment by jjjchens235** [comment]
Oh I see what you meant. You ran this program 3x, once for each account and it's faster than the other program.
Thought you mis-typed because I feel this program is quite slow as it refreshes the search progress after each search. 
That's great news!
