### ISSUE TITLE
[Feature Request] Ability to run in a docker

### ISSUE THREAD

**Issue by Fluff663** [jjjchens235/bing-rewards#206]

**Comment by Killerherts** [comment]
Wouldn't this require setup.py to be part of BingRewards.py?
As techniquely the script is actualy 2 different scripts

**Comment by malesci** [comment]
@jjjchens235 it would be great to have a docker container with everything you need to run the script.
Can you add it to your backlog? do you think you can do it in a short time? 
thank you very much as always

**Comment by jjjchens235** [comment]
@malesci  I've never implemented a docker container in my life, but I think you're right, this is the logical next step, especially since there have been a lot of issues recently regarding environments. It probably won't be in a short time though-  I have a few other priorities outside of this project right now. 

@Killerherts Again, excuse my ignorance on Docker, but my preliminary plan would be something like this:
1. user passes in `setup.py` command-line arguments to docker as env variables like so 
```sh
docker run -e email=<email> -e password=password ...
```
2. The DockerFile `ENTRYPOINT` will call a script `myStartupScript.sh` which does the following
   - If there are environment variables passed in, run `setup.py` with the passed-in environment variables
   - Run `BingRewards.py`

**Comment by jjjchens235** [comment]
Ok, so I spent a little time messing with this. 

Wanted to get BingRewards.py running with as little hassle as possible, so in the Dockerfile, I copied my local config file into the container as a shortcut for now.

Simplified Dockerfile:
```sh
FROM python:3.9.5

# install google chrome
RUN wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -
RUN sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list'
RUN apt-get -y update
RUN apt-get install -y google-chrome-stable


COPY /BingRewards /BingRewards
WORKDIR /BingRewards

RUN pip install --upgrade pip

RUN pip install -r requirements.txt

#CMD ["python", "./BingRewards.py"]
```

After image is built, we can run our container:
```sh
# go into docker container
docker run -it bing_rewards bash
# manually delete chromedriver so that we redownload it
rm drivers/chromedriver
# must run in no sand box mode
python BingRewards.py -nsb
```

Looks like we run into the same chrome v103 issue [here](https://github.com/jjjchens235/bing-rewards/issues/239).

But it's a good start.

Action items:
1. After upstream v103 issue is fixed, make sure the simplified container runs
2. Update container to NOT copy from local directory, figure out how to set-up config natively, consider the post above.

**Comment by malesci** [comment]
hello I'm experienced that the following changes are good in order to have all correctly running on container.

```
ARG VERSION=3.9-slim
FROM python:$VERSION

# Installs google-chrome, chromedriver
RUN set -ex \
    && apt-get update \
    && apt-get install -y gnupg curl wget unzip ca-certificates --no-install-recommends \
    && wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | \
    gpg --no-default-keyring --keyring gnupg-ring:/etc/apt/trusted.gpg.d/google.gpg --import \
    && chmod 644 /etc/apt/trusted.gpg.d/google.gpg \
    && echo "deb https://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list \
    && apt-get update -y \
    && apt-get install -y google-chrome-stable\
    && CHROME_VERSION=$(google-chrome --product-version | grep -o "[^\.]*\.[^\.]*\.[^\.]*") \
    && CHROMEDRIVER_VERSION=$(curl -s "https://chromedriver.storage.googleapis.com/LATEST_RELEASE_$CHROME_VERSION") \
    && wget -q --continue -P /chromedriver "https://chromedriver.storage.googleapis.com/$CHROMEDRIVER_VERSION/chromedriver_linux64.zip" \
    && unzip /chromedriver/chromedriver* -d /usr/local/bin/
   
# Set display port as an environment variable
ENV DISPLAY=:99

...
...
```

and, specially for using selenium with python in a docker container, I did following changes on driver.py file otherwise [Chrome was to fail or crash](http://crbug.com/715363).
<img width="1385" alt="Schermata 2022-07-08 alle 22 23 12" src="https://user-images.githubusercontent.com/36844281/178067126-5ba5f79f-2677-4f71-87c4-d9a7dec082a9.png">


Regards
Mariano

**Comment by jjjchens235** [comment]
Hey malesci,  i looked at your version and I'm not sure what the difference is here?

I have to main questions though:
1. what is the end goal of this docker container? I'm trying to figure out if using the `COPY` from local directory into the docker container satisfies the requirement. Or if this needs to be done via a `git clone`. I would prefer the former b/c the `setup.py` config does not need to be accounted for.
2. In your implementation, you're downloading the chromedriver via wget. However, the bing-rewards script also has chromedriver download logic. For this reason, I was thinking of letting the python script handle this, rather than the dockerfile, so as to have to maintain download logic in two separate places.

thoughts?

**Comment by malesci** [comment]
Hello @jjjchens235 

> 1. what is the end goal of this docker container? I'm trying to figure out if using the `COPY` from the local directory into the docker container satisfies the requirement. Or if this needs to be done via a `git clone`. I would prefer the former b/c the `setup.py` config does not need to be accounted for.

yes you are right, I'm using this sample in a similar context but not exacly the same, by the way yes you can use `COPY` from the local directory into the docker container satisfies the requirement for sure.

> 2. In your implementation, you're downloading the chromedriver via wget. However, the bing-rewards script also has chromedriver download logic. For this reason, I was thinking of letting the python script handle this, rather than the dockerfile, so as to have to maintain download logic in two separate places.

Ok no issue,  if bing-rewards script also has chromedriver download logic it will be good to leverage on it, avoiding adding additional logics.


In any case, in my Dockerfile sample I would like just to hi light a couple of tips that I did:
- Fix “apt-key is deprecated. Manage keyring files in trusted.gpg.d instead”
- Set the display port (99) as Selenium is using this. It will avoid some crushes.
- I also recummend to create a dedicated user for running work


And also I would like to suggest the upper mentioned changes on driver.py
![](https://user-images.githubusercontent.com/36844281/178067126-5ba5f79f-2677-4f71-87c4-d9a7dec082a9.png)



regards

**Comment by jjjchens235** [comment]
Thank you @malesci  and @Killerherts 

Killerherts- would it make sense just to move `setup.py` to the `BingRewards` sub-directory?

**Comment by Killerherts** [comment]
> Thank you @malesci and @Killerherts
> 
> Killerherts- would it make sense just to move `setup.py` to the `BingRewards` sub-directory?

Not necessary anymore I'll push my repo in coming days I just got busy. @jjjchens235 my plan was just to let the docker sit at bash and people can run setup.py or BingRewards.py accordingly. My image is about 775mb now and there is only 2 line changes to driver.py and they don't seem to effect the non docker version in anyway.

**Comment by jjjchens235** [comment]
This will be moved to master shortly, thank you @malesci for your guidance  and @Killerherts for the dev implementation

d75eca1
