### ISSUE TITLE
Errors installing requirements, Ubuntu

### ISSUE THREAD

**Issue by mgrimace** [jjjchens235/bing-rewards#238]
Hello,
I receive the following errors after running `pip install -r BingRewards/requirements.txt`. The BingRewards.py script still seems to complete normally so posting here just in case it's something that needs fixing

```
ERROR: launchpadlib 1.10.13 requires testresources, which is not installed.
ERROR: googleapis-common-protos 1.56.2 has requirement protobuf<4.0.0dev,>=3.15.0, but you'll have protobuf 4.21.1 which is incompatible.
Installing collected packages: python-dateutil, async-generator, sniffio, sortedcontainers, outcome, trio, h11, wsproto, trio-websocket, PySocks, urllib3, selenium, charset-normalizer, requests, uritemplate, pyasn1, pyasn1-modules, cachetools, rsa, google-auth, protobuf, googleapis-common-protos, google-api-core, pyparsing, httplib2, google-auth-httplib2, google-api-python-client, requests-oauthlib, google-auth-oauthlib
  WARNING: The script normalizer is installed in '/home/ubuntu/.local/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  WARNING: The scripts pyrsa-decrypt, pyrsa-encrypt, pyrsa-keygen, pyrsa-priv2pub, pyrsa-sign and pyrsa-verify are installed in '/home/ubuntu/.local/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  WARNING: The script google-oauthlib-tool is installed in '/home/ubuntu/.local/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
Successfully installed PySocks-1.7.1 async-generator-1.10 cachetools-5.2.0 charset-normalizer-2.0.12 google-api-core-2.8.2 google-api-python-client-2.51.0 google-auth-2.8.0 google-auth-httplib2-0.1.0 google-auth-oauthlib-0.5.2 googleapis-common-protos-1.56.2 h11-0.13.0 httplib2-0.20.4 outcome-1.2.0 protobuf-4.21.1 pyasn1-0.4.8 pyasn1-modules-0.2.8 pyparsing-3.0.9 python-dateutil-2.8.2 requests-2.28.0 requests-oauthlib-1.3.1 rsa-4.8 selenium-4.2.0 sniffio-1.2.0 sortedcontainers-2.4.0 trio-0.21.0 trio-websocket-0.9.2 uritemplate-4.1.1 urllib3-1.26.9 wsproto-1.1.0
```

**Comment by heximing** [comment]
I have the same ERROR, but I think the requirement is still installed anyway because, if I re-install the requirement, it says everything was installed.

However, I get errors when setting up the account. When I run "setup.py", it says:

C:\Users\xhe\Downloads\WPy64-37120\pypy3.7-v7.3.7-win64>python C:\Users\xhe\Downloads\PyCharmPortable\PycharmProjects\bing-rewards-master\setup.py
*MS Rewards Email: ************@hotmail.com (I blank out my email address for privacy)
Traceback (most recent call last):
  File "C:\Users\xhe\Downloads\PyCharmPortable\PycharmProjects\bing-rewards-master\setup.py", line 104, in <module>
    main()
  File "C:\Users\xhe\Downloads\PyCharmPortable\PycharmProjects\bing-rewards-master\setup.py", line 93, in main
    new_credentials = __prompt_simple_input(existing_credentials)
  File "C:\Users\xhe\Downloads\PyCharmPortable\PycharmProjects\bing-rewards-master\setup.py", line 42, in __prompt_simple_input
    password = __encode(getpass.getpass("*Password: "))
  File "C:\Users\xhe\Downloads\WPy64-37120\pypy3.7-v7.3.7-win64\lib-python\3\getpass.py", line 103, in win_getpass
    msvcrt.putwch(c)
  File "C:\Users\xhe\Downloads\WPy64-37120\pypy3.7-v7.3.7-win64\lib_pypy\msvcrt.py", line 112, in putwch
    _lib._putwch(ord(ch))
TypeError: initializer for ctype 'wchar_t' must be a unicode string of length 1, not int

**Comment by heximing** [comment]
Never mind. Running it with "-d msedge" will (kind of) work, but with the same error stated in Issue #239.

Thanks anyways.

**Comment by jjjchens235** [comment]
New docker image should solve all of these issues
