### ISSUE TITLE
BingRewards.py instantly closes

### ISSUE THREAD

**Issue by Robi2003** [jjjchens235/bing-rewards#44]
Hello,
so as I mentioned in the title... BingRewards.py shows up for less than a second and disappears.

I installed everything as explained. And I entered my account details in setup.py

**Comment by jjjchens235** [comment]
Can you post the message from logs/error.log?

**Comment by Robi2003** [comment]
where can I find the folder "logs"?

**Comment by jjjchens235** [comment]
The project structure is bing-rewards-master/BingRewards/logs.
If you can't find it, even better would be if you can copy/paste the output of the terminal.

**Comment by Robi2003** [comment]
![grafik](https://user-images.githubusercontent.com/21022093/94345220-b2971300-0024-11eb-9364-3a6d88313d3a.png)

**Comment by jjjchens235** [comment]
You don't have one of the required python libraries installed. 
Please go back to the 'Getting Started' section and re-try step #3 (requirements.txt).

**Comment by Robi2003** [comment]
![grafik](https://user-images.githubusercontent.com/21022093/94346934-5afea480-0030-11eb-88d6-a059c92c1c28.png)

**Comment by jjjchens235** [comment]
i see. I think you have some permission issues with pip. If you don't want to change permissions try running pip install --user -r requirements.txt. Note the extra --user flag.

All this is a moot point though because this program will not work for non-USA users as MS rewards sets up their website differently for each country. I will post this in the README soon, sorry for any mix-up.

**Comment by Robi2003** [comment]
![grafik](https://user-images.githubusercontent.com/21022093/94445382-ab4c4280-01a7-11eb-9cc5-e0c681cde1b6.png)

yeah, it's not working

**Comment by jjjchens235** [comment]
It looks like pip was actually uninstalled when you ran requirements.txt in the 2nd screen-shot.
However, on the bright side, it looks like all the packages were installed successfully. 
Try running BingRewards/BingRewards.py.

You probably should re-install pip, here are the instructions: https://stackoverflow.com/questions/61518863/pip-has-uninstalled-itself-but-i-do-not-know-what-caused-it

**Comment by Robi2003** [comment]
well, yeah... it still says the same like in the first screenshot.

**Comment by jjjchens235** [comment]
Ok my new hypothesis is this, based on the first screenshot it looks like dateutil was 'collected', but it was never installed because it error'ed out.

At this point we need to start over. I think these are the following steps:
1) re-install pip: `https://stackoverflow.com/questions/61518863/pip-has-uninstalled-itself-but-i-do-not-know-what-caused-it`
2) inside the terminal run `git pull`. The newest version of this program has an updated requirements file.
3) run `pip install -r requirements.txt`

I would understand if this is too many steps for you at this point. I want to repeat one more time that even if we get past these steps, the program will not work for German users.

**Comment by Robi2003** [comment]
![grafik](https://user-images.githubusercontent.com/21022093/94581494-73163400-027b-11eb-95dd-0f4a09648544.png)

It seems to work now.
Is it somehow possible to switch my Account into an US account?


![grafik](https://user-images.githubusercontent.com/21022093/94581684-a22ca580-027b-11eb-9f1e-a0eebb586c7c.png)


And then using a VPN with an IP from the US?

**Comment by jjjchens235** [comment]
Wow, that was quick.

You could try using a VPN, but based on reddit, it seems like MS bans pretty quickly for this. Not sure how true this is.
https://www.google.com/search?sxsrf=ALeKk03ag8Tlsmtb6AmiZAWGOAMUsOodpw%3A1601394443427&ei=C1dzX7XKGY3Y-gTfjqfYBQ&q=ms+rewards+reddit+vpn&oq=ms+rewards+reddit+vpn&gs_lcp=CgZwc3ktYWIQAzIFCCEQoAE6BAgAEEc6CAghEKABEIsDOgUIIRCrAjoGCAAQFhAeOggIIRAWEB0QHlCrBVjBCWCGC2gAcAJ4AIABbIgBvwOSAQM0LjGYAQCgAQGqAQdnd3Mtd2l6yAEIuAECwAEB&sclient=psy-ab&ved=0ahUKEwj1-8eX247sAhUNrJ4KHV_HCVsQ4dUDCA0&uact=5

**Comment by Robi2003** [comment]
I would try it with a new account set from the start as a US account

**Comment by jjjchens235** [comment]
Sounds like a plan, glad we got it resolved, and thanks for your patience!
