### ISSUE TITLE
Minecraft Live quiz tries to open Microsoft Store

### ISSUE THREAD

**Issue by codenotworking** [jjjchens235/bing-rewards#45]
I noticed the code was stuck on here for about 10-15 minutes.  Turns out a pop-up appears trying to open the Microsoft Store
```
>> Trying Dont miss Minecraft Live
              >>> Starting quiz
                  <<< Could not detect quiz overlay
              >>> Starting quiz2 (no overlay)
              >>> Could not find quiz2 progress elements
           << Failed to complete Dont miss Minecraft Live
```
Screenshots:
<img src="https://i.imgur.com/L9T3QFv.png" width="250" />

<img src="https://i.imgur.com/nBhKhny.png" />

**Comment by jjjchens235** [comment]
Hey codenotworking, thanks for the heads up.

I don't have access to a machine with the Microsoft app store on it, so I can't test this directly (I get an alternative quiz about cricket lol).

I tried testing this with zoom, since it gives a similar pop-up to the one you got, using this link:
https://zoom.us/test

I updated the code to always accept these pop-ups by following these steps:
https://stackoverflow.com/questions/61307780/how-can-i-press-the-open-application-button-in-selenium?noredirect=1&lq=1

The code I ended up using in driver.py was this:
`options.add_experimental_option("prefs", {"profile.default_content_setting_values.geolocation" : 1, "protocol_handler": {"excluded_schemes": {"zoommtg": "false"}}}) # geolocation permission, 0=Ask, 1=Allow, 2=Deny`

However, after messing around for 1.5 hours, I wasn't able to get this to work. Furthermore, even if it did work for zoom, I'm not sure what the protocol name for Microsoft Store would be, I couldn't find anything online.

Also, what I don't get is why it doesn't immediately error out inside quiz2(), the exception should have been raised immediately when the question pane is not found?  https://github.com/jjjchens235/bing-rewards/blob/424948a02332c76159040fd37ba9fe73f2ba806b/BingRewards/src/rewards.py#L528

**Comment by jjjchens235** [comment]
Ok so for some reason, this offer doesn't show up on my main account, but it does on my test account. 
The TL,DR is that I don't think this is fixable still, but here's my hypothesis:

When the offer is first clicked, it redirects me to a completely blank page, with a blank url. After 15 minutes or so it finally gets to quiz2() and there a TimeoutException occurs. So it's exact same error message you get. The only difference is I don't get a popup for the MS store since I don't have MS Store on my device. Therefore, 

I think the pop-up isn't the real issue here. Rather, there is something within the Minecraft link that is not rendering properly, and selenium takes forever to scrape it.

**Comment by codenotworking** [comment]
No worries.  Luckily it's only a rare occasion Bing has these quiz's that require to open the Microsoft Store.

**Comment by jjjchens235** [comment]
This hasn't been an issue in a while, closing now.
