### ISSUE TITLE
RuntimeError: Logged in, but not United States user

### ISSUE THREAD

**Issue by deanorocko** [jjjchens235/bing-rewards#47]
As title, after updating this morning it's now immediately failing with the above error

RuntimeError: Logged in, but not United States user

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "BingRewards.py", line 142, in <module>
    __main(args[0], arg1.replace("-", ""))
  File "BingRewards.py", line 82, in __main
    rewards.complete_all(hist_log.get_search_hist())
  File "C:\users\x\Desktop\bing-rewards-master\BingRewards\src\rewards.py", line 886, in complete_all
    driver = self.__complete_edge_search()
  File "C:\users\x\Desktop\bing-rewards-master\BingRewards\src\rewards.py", line 733, in __complete_edge_search
    self.__login(driver)
  File "C:\users\x\Desktop\bing-rewards-master\BingRewards\src\rewards.py", line 104, in __login
    raise RuntimeError("Did NOT log in successfully")
RuntimeError: Did NOT log in successfully

**Comment by jjjchens235** [comment]
I added a check to make sure the user is an United States user. 

If you are not in the USA, but this program was working for you before, let me add your country to the list of accepted countries.

Can you tell me what your URL redirects to after you have logged in on https://login.live.com/?
For example, mine redirects to https://account.microsoft.com/?lang=en-US&refd=account.live.com&refp=landing&mkt=EN-US

**Comment by deanorocko** [comment]
Hey,

Thanks for getting back to me!  I'm in the UK and here's the URL I get.

https://account.microsoft.com/?lang=en-GB&refd=account.live.com&refp=landing&mkt=EN-GB

Thanks, appreciate the work :)

**Comment by yottamoto** [comment]
I'm in Germany and get this URL:

https://account.microsoft.com/?lang=de-DE&refd=account.live.com&refp=landing&mkt=DE-DE

I also have the same problem.

**Comment by jjjchens235** [comment]
@yottamoto 
The program is purposefully terminating because Germany is considered an invalid market, i.e. the German web site has different web elements compared to the US one.

If you would like to add Germany as a valid market, adjust this line of code:
https://github.com/jjjchens235/bing-rewards/blob/fc5d6e99e26aed8eed58c9e9b967e61886ce8ab6/BingRewards/src/rewards.py#L101

The new code should be
`VALID_MARKETS = ['mkt=EN-US', 'mkt=EN-GB', 'mkt=DE-DE']`

If the searches and offers work, please let me know, and I will update the code in the next release.
