### ISSUE TITLE
Selenium not found

### ISSUE THREAD

**Issue by personthegreat** [jjjchens235/bing-rewards#70]
It's giving me a driver not found error, but I have the latest Selenium installed.

**Comment by chris987789** [comment]
what OS and browser are you using?

**Comment by personthegreat** [comment]
I'm using Windows 10 and I'm assuming its Chrome since that's what the program seems to use (although I mainly use Microsoft Edge). 
I'm not quite sure how to find error.log but the error is in line 6 of driver.py and it says "ModuleNotFoundError: No module named 'selenium'"

**Comment by chris987789** [comment]
It appears you haven't installed the modules:

If you don't already have Python 3 installed, visit https://www.python.org/downloads/.
Now install the dependencies using the BingRewards/requirements.txt file included in the repo: pip install -r BingRewards/requirements.txt.

**Comment by personthegreat** [comment]
when I do that, it says that all the requirements are met. Yet it's still giving me a selenium error.

**Comment by chris987789** [comment]
open command prompt and type 'pip list' copy what you get into here, then get the error log from BingRewards/log/ folder and copy that here

**Comment by personthegreat** [comment]
Package         Version
--------------- -------
pip             21.1.1
python-dateutil 2.8.1
selenium        3.141.0
six             1.15.0
urllib3         1.26.4

I can't find the log folder in the BingRewards folder, I only have src, BingRewards.py, and requirements.txt.

**Comment by personthegreat** [comment]
This is still problem for me, can anyone help?

**Comment by jjjchens235** [comment]
You can't find the log folder b/c the code never got far enough to create it.

I'm not exactly sure what to say here though... on one hand you're getting an error saying that Selenium isn't installed and on the other hand, `pip list` shows that you have Selenium installed. 

If I were you, I would create a .py file with one line:
`import selenium`

Then figure out how to get this one line of code running.

I'm closing this out b/c this issue is beyond the scope of this project
