### ISSUE TITLE
Can't input password

### ISSUE THREAD

**Issue by axv2655** [jjjchens235/bing-rewards#76]
I tried to input password after putting email and it wont allow me. I opened it in powershell and it gave this error
![image](https://user-images.githubusercontent.com/84362717/118580867-40f80a80-b756-11eb-9b57-d498e1c808ff.png)

**Comment by jjjchens235** [comment]
The only thing I can think of is maybe using the 'command prompt' program instead of powershell?

**Comment by axv2655** [comment]
it doesnt change anythin

**Comment by jjjchens235** [comment]
Looking at this more closely, I don't think the error is inputting the password.

The error that is being thrown is 'No such file or directory.'

The error msg is a little misleading because if the file doesn't exist, open('w') should be able to create this file.

That leaves the directory to be the problem. I think the directory doesn't exist. Is it possible you deleted either the 'BingRewards' or 'src' sub-directories?

**Comment by jjjchens235** [comment]
Closing due to lack of response
