### ISSUE TITLE
Error checking rewards status -  local variable 'IS_LEVEL_TWO' referenced before assignment

### ISSUE THREAD

**Issue by briantho** [jjjchens235/bing-rewards#79]
Hi, I just started using this awesome program. It seems to work, but after completing everything I get an error that says:

   Error checking rewards status -  local variable 'IS_LEVEL_TWO' referenced before assignment

Again it seems to work, however i get this error at the end. Please let me know what I'm doing wrong, or if this is a bug. Thanks

Also, I'm running Windows 10 21h1, and am using the latest python (3.95) with all dependencies installed and up to date

**Comment by jjjchens235** [comment]
Hi I tried with both my Level 1 and Level 2 account and didn't get this error. 
I suspect the stats element on your Microsoft Rewards portal is different, are you in the USA?

**Comment by briantho** [comment]
The computer I'm running this on is in California. I am currently out of the country on a trip, but use anydesk to remote control the pc. I don't see that as being the issue, though anything is a possibility. Again, the pc is located in california and has a US Ip address, and i just remotely connect to it. I'm not using a vpn or anything fancy, just anydesk to remotely monitor/control it. 

Anyway, is there any to debug why this is happening?

**Comment by jjjchens235** [comment]
That's a pretty cool set-up!

Regarding debugging, I would first look up where the error is happening inside logs/error.log.

I suspect the error is thrown from this [line](https://github.com/jjjchens235/bing-rewards/blob/218b4b18b3edbc847b478c276d31bb6365c39fd8/BingRewards/src/rewards.py#L893)

If so, it's because IS_LEVEL_TWO is never set, it should be set in this if/elif [block](https://github.com/jjjchens235/bing-rewards/blob/218b4b18b3edbc847b478c276d31bb6365c39fd8/BingRewards/src/rewards.py#L888)

To debug this further, you need to check what items are in the list `stats`, which is being set [here](https://github.com/jjjchens235/bing-rewards/blob/218b4b18b3edbc847b478c276d31bb6365c39fd8/BingRewards/src/rewards.py#L881)

**Comment by briantho** [comment]
Hmm, interesting. So, I don't have an error.log i only have a run.log and a search.log 
How do I check what is in stats?

**Comment by DKL72** [comment]
I'm having the same issue. My 'stats' list is only 4 in length so IS_LEVEL_TWO is never set.

**Comment by DKL72** [comment]
In my case I am Level 2 but I am only getting 4 stats in this order:  Donated, Available, Lifetime, Points Earned

**Comment by DKL72** [comment]
So apparently they somehow enabled "Giving Mode" this month which messes up the summary. I did not even know I was donating my points this month. I disabled this mode and now everything works.

**Comment by jjjchens235** [comment]
Wow, awesome discovery, I would never have figured that out, so I'm glad you did!

Closing out for now.

**Comment by briantho** [comment]
Yep, disabling "Giving Mode" worked. Thanks for figuring out the problem

**Comment by DKL72** [comment]
My pleasure !
