### ISSUE TITLE
Feature Request: auto update program

### ISSUE THREAD

**Issue by briantho** [jjjchens235/bing-rewards#99]
Title pretty much says it all, in other words figure out a way to auto update bing rewards every time a new release comes out. This could be done on the start of bing rewards, or possibly via python and the pip command. Either way is fine with me. What do you think? Could this be done?

**Comment by AndrewChqng** [comment]
I just added git update into the bash script, works pretty well for me

**Comment by jjjchens235** [comment]
@AndrewChqng  
Are you referring to `git remote update`? 
This command seems very similar to `git fetch` but wouldn't you need to actually merge the remote changes in?

OP, I would advocate creating a bash script `BingRewards.sh` like so:
```bash
git checkout master
git pull
python BingRewards.py
```

Instead of running `python BingRewards.py` you would now run `./BingRewards.sh`

**Comment by AndrewChqng** [comment]
Sorry I meant git pull , I should know this of the top of my head by now 🤦🏻‍♂️, I'll add what you suggest though👍.

**Comment by jjjchens235** [comment]
OP, if this doesn't fix your issue, feel free to re-open
